language: php

php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.2" ]]; then composer require php-coveralls/php-coveralls; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then composer require --dev vimeo/psalm:1.1.9; fi

script:
  - tools/check-syntax.sh
  - ant
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then vendor/bin/psalm; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.2" ]]; then php vendor/bin/php-coveralls -v; fi
