---

name: Documentation

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master, release-*]
    paths:
      - '**.md'
  pull_request:
    branches: [master, release-*]
    paths:
      - '**.md'

jobs:
  quality:
    name: Quality checks
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Lint markdown files
        uses: nosborn/github-action-markdown-cli@v3.1.0
        with:
          files: .
          ignore_path: .markdownlintignore

      - name: Perform spell check
        uses: codespell-project/actions-codespell@master
        with:
          path: '**/*.md'
          check_filenames: true
          ignore_words_list: tekst
