---
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['**']
  pull_request:
    branches: [master, release-*]

jobs:
  basic-tests:
    name: Unit tests, PHP ${{ matrix.php-versions }}, ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        php-versions: ['8.3', '8.4', '8.5']

    steps:
      - name: Setup PHP, with composer and extensions
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: error_reporting=E_ALL^E_DEPRECATED
          extensions: intl, mbstring, sodium, xml
          coverage: xdebug

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v6

      - name: Get composer cache directory (linux)
        if: ${{ matrix.operating-system == 'ubuntu-latest' }}
        run: echo COMPOSER_CACHE="$(composer config cache-files-dir)" >> "$GITHUB_ENV"

      - name: Get composer cache directory (windows)
        if: ${{ matrix.operating-system == 'windows-latest' }}
        run: echo COMPOSER_CACHE="$(composer config cache-files-dir)" >> "$env:GITHUB_ENV"

      - name: Cache composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ env.COMPOSER_CACHE }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Decide whether to run code coverage or not
        if: ${{ matrix.php-versions != '8.3' || matrix.operating-system != 'ubuntu-latest' }}
        run: |
          echo "NO_COVERAGE=--no-coverage" >> $GITHUB_ENV

      - name: Run unit tests
        run: |
          echo $NO_COVERAGE
          ./vendor/bin/phpunit $NO_COVERAGE

      - name: Save coverage data
        if: ${{ matrix.php-versions == '8.3' && matrix.operating-system == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v6
        with:
          name: build-data
          path: ${{ github.workspace }}/build

  security:
    name: Security checks
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup PHP, with composer and extensions
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml
          tools: composer:v2
          coverage: none

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - uses: actions/checkout@v6

      - name: Get composer cache directory (linux)
        run: echo COMPOSER_CACHE="$(composer config cache-files-dir)" >> "$GITHUB_ENV"

      - name: Cache composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ env.COMPOSER_CACHE }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Security check for locked dependencies
        uses: symfonycorp/security-checker-action@v5

      - name: Update Composer dependencies
        run: composer update --no-progress --prefer-dist --optimize-autoloader

      - name: Security check for updated dependencies
        uses: symfonycorp/security-checker-action@v5

  phplinter:
    name: 'PHP-Linter'
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.3', '8.4', '8.5']

    uses: simplesamlphp/simplesamlphp-test-framework/.github/workflows/reusable_phplinter.yml@v1.11.0
    with:
      php-version: ${{ matrix.php-version }}

  linter:
    name: 'Linter'
    strategy:
      fail-fast: false

    uses: simplesamlphp/simplesamlphp-test-framework/.github/workflows/reusable_linter.yml@v1.11.0
    with:
      enable_eslinter: false
      enable_jsonlinter: true
      enable_stylelinter: false
      enable_yamllinter: true

  quality:
    name: Quality control
    runs-on: [ubuntu-latest]
    needs: [basic-tests]

    steps:
      - name: Setup PHP, with composer and extensions
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - uses: actions/checkout@v6

      - name: Get composer cache directory (linux)
        run: echo COMPOSER_CACHE="$(composer config cache-files-dir)" >> "$GITHUB_ENV"

      - name: Cache composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ env.COMPOSER_CACHE }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - uses: actions/download-artifact@v7
        with:
          name: build-data
          path: ${{ github.workspace }}/build

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: PHP Code Sniffer
        continue-on-error: true
        run: php vendor/bin/phpcs src/

      - name: Psalm
        continue-on-error: true
        run: php vendor/bin/psalm --show-info=true

      - name: Psalter
        run: php vendor/bin/psalter --issues=UnnecessaryVarAnnotation --dry-run
